spring:
  application:
    name: SocialMedia-API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social_media_api
    hikari:
      schema: public
      username: postgres
      password: mustafa
  data:
    mongodb:
      uri: mongodb://localhost:27017/social_media_api

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      boot:
        allow_jdbc_metadata_access: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
        SQL: debug
      springframework:
        security: debug
